templates:
  global:
    content_filter:
      reject: "*.rar"

    # Ensure Mac friendly filenames/paths
    pathscrub: mac

    quality: 720p+ hdtv+

    # Add the output plugin for Transmission
    transmission:
      netrc: /root/.netrc
      removewhendone: yes 	# Remove entries when max ratio reached

  # TV shows
  tv:
    exists_series: /c/Downloads/_TV

    thetvdb_lookup: yes
    set:
      path: "/c/Downloads/_TV/{{ series_name|replace(':',' -') }}/Season {{ series_season }}/"

    configure_series:
      from:
        thetvdb_favorites:
          account_id: F8B4B7D7E60FE985
          strip_dates: yes

    discover:
      what:
        - emit_series: yes
      from:
        - torrentz: verified
        - kat:
            category: tv
            verified: yes
        - piratebay:
            category: 207	# "HD - TV"
            sort_by: seeds

  # Movies
  movies:
    exists_movie: /c/Downloads/_Movies
    seen_movies: strict

    set:                                                                                                               
      path: /c/Downloads/_Movies

    movie_queue: yes

    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz: verified
        - kat:
            category: movies
            verified: yes
        - piratebay:
            category: 207	# "HD - Movies"
            sort_by: seeds

    # Don't download movies already rated 
    crossmatch:
      from:
        - imdb_list:
            user_id: ur26971513
            list: ratings
      fields:
        - imdb_id
      action: reject

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and add to the movie queue
  Watchlist:
    imdb_list:
      list: watchlist
      user_id: ur26971513
    accept_all: yes
    queue_movies: yes

  Movies:
    template:
      - movies

  TV:
    template:
      - tv
