presets:
  # Applies to all sections
  global:
    # Files we're not interested in
    content_filter:
      # RAR is not an appropriate file format for BitTorrent
      reject: "*.rar"

  # If the decision is made to download, apply these settings
  downloader:
    # Send to Transmission
    transmission:
      netrc: /root/.netrc
      path: /c/Downloads

      # Remove Transmission entries when 'done'
      removewhendone: yes

      # Ensure Mac friendly filenames/paths
      # 'pathscrub' not yet available??
      #pathscrub: mac

    # Send a Pushover notification for new downloads
    pushover:
      userkey: G49sadwAjzpZCV51AEJowW1YbBFlSk
      apikey: 9lnmJP1quht0ZzMXDK2Bq6KnqBpQJm
      device: SGS2

  # TV shows
  tv:
    # Check if the TV show already exists locally
    exists_series: /c/Downloads/_TV

    # Fetch show details from The TV DB
    #   and set the path and filename to something
    #   appropriate
    thetvdb_lookup: yes
    set:
      content_filename: "{{ series_id }} - {{ ep_name|default('Unnamed')|replace(':', ' -') }} - {{ quality|upper }}"
      path: "/c/Downloads/_TV/{{ series_name|replace(':',' -') }}/Season {{ series_season }}/"

    # Import TV series to download from thetvdb.com
    import_series:
      from:
        thetvdb_favorites:
          account_id: F8B4B7D7E60FE985
          strip_dates: yes

    # Override the paths for some shows
    series:
      # Overrides
      - BBC Horizon
      - Top Gear:
          path: "/c/Downloads/_Scott/{{ series_name|replace(':',' -') }}/Season {{ series_season }}/"

  # Movies
  movies:
    # Check if the movie already exists locally
    exists_movie: /c/Downloads/_Movies
    seen_movies: strict

    # Set the download path for movies
    set:                                                                                                               
      path: /c/Downloads/_Movies   

    # Set quality: only DVDRip or better and only up-to 720p 
    #   (1080p pushes the 2008 MacMini a bit too hard)
    quality: hdrip-bluray <=720p

    # Apply to the movie queue
    movie_queue: yes

    # Go out into the world and find torrents
    #   for movies in the queue
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz
      type: movies

    # Don't download movies already rated 
    #   (i.e. already seen)
    crossmatch:
      from:
        - imdb_list:
            list: ratings
            user_id: ur26971513
      fields:
        - imdb_id
      action: reject

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and build the movie queue
  IMDB-Watchlist:
    imdb_list:
      list: watchlist
      user_id: ur26971513
    accept_all: yes

    # Add to the movie queue
    queue_movies: yes

  # Newly available Movies feed
  Torrentz-Movies:
    rss: http://torrentz.eu/feed_verified?q=movies
    preset:
      - movies
      - downloader

  # Newly available TV shows feed
  Torrentz-TV:
    rss: http://torrentz.eu/feed_verified?q=tv
    preset:
      - tv
      - downloader
