templates:
  # Applies to all sections
  global:
    # Files we're not interested in
    content_filter:
      # RAR is not an appropriate file format for BitTorrent
      reject: "*.rar"

    # Ensure Mac friendly filenames/paths
    pathscrub: mac

    quality: 720p+ hdtv+

  # If the decision is made to download, apply these settings
  downloader:
    # Send to Transmission
    transmission:
      netrc: /root/.netrc

      # Remove Transmission entries when 'done'
      removewhendone: yes

  # TV shows
  tv:
    # Check if the TV show already exists locally
    exists_series: /c/Downloads/_TV

    # Fetch show details from The TV DB
    #   and set the path and filename to something
    #   appropriate
    thetvdb_lookup: yes
    set:
      path: "/c/Downloads/_TV/{{ series_name|replace(':',' -') }}/Season {{ series_season }}/"

    # Import TV series to download from thetvdb.com
    configure_series:
      from:
        thetvdb_favorites:
          account_id: F8B4B7D7E60FE985
          strip_dates: yes

    # Go out into the world and find torrents
    #   for series in the queue
    discover:
      what:
        - emit_series: yes
      from:
        - torrentz: verified
        - kat:
            category: tv
            verified: yes
        - piratebay:
            # 207 = "HD - TV"
            category: 207
            sort_by: seeds

  # Movies
  movies:
    # Check if the movie already exists locally
    exists_movie: /c/Downloads/_Movies
    seen_movies: strict

    # Set the download path for movies
    set:                                                                                                               
      path: /c/Downloads/_Movies

    # Apply to the movie queue
    movie_queue: yes

    # Go out into the world and find torrents
    #   for movies in the queue
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz: verified

    # Don't download movies already rated 
    #   (i.e. already seen)
    crossmatch:
      from:
        - imdb_list:
            list: ratings
            user_id: ur26971513
      fields:
        - imdb_id
      action: reject

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and build the movie queue
  IMDB-Watchlist:
    imdb_list:
      list: watchlist
      user_id: ur26971513
    accept_all: yes

    # Add to the movie queue
    queue_movies: yes

  # Newly available Movies feed
  Torrentz-Movies:
    rss: http://movieboot.com/rss/bdaf0f48a5ab69d8d3e3d18e12b26d23/
    template:
      - movies
      - downloader

  # Newly available TV shows feed
  Torrentz-TV:
    rss: http://showrss.info/feeds/all.rss
    template:
      - tv
      - downloader
