secrets: secrets.yml

templates:
  global:
    content_filter:
      reject:
        - '*.rar'
        - '*HEVC*'

    # Ensure Mac friendly filenames/paths
    pathscrub: mac

  # TV shows
  tv:
    exists_series:
      path: '{{ secrets.general.tv_path }}'
      allow_different_qualities: yes

    trakt_lookup: yes
    set:
      path: '/c/Downloads/_TV/{{ series_name|replace(":"," -") }}/Season {{ series_season }}'

    quality: hdtv+

    # Add the output plugin for Transmission
    transmission:
      netrc: '{{ secrets.general.netrc_path }}'

  # Movies
  movies:
    exists_movie: '{{ secrets.general.movies_path }}'
    seen_movies: strict

    set:                                                                                                               
      path: '{{ secrets.general.movies_path }}'

    quality: 720p+ hdtv+

    # Don't download movies already rated 
    crossmatch:
      from:
        - imdb_list:
            list: ratings
            user_id: '{{ secrets.imdb.user_id }}'
      fields:
        - imdb_id
      action: reject

    # Attempt to prevent bogus downloads
    imdb_required: yes

    # Add the output plugin for Transmission
    transmission:
      netrc: '{{ secrets.general.netrc_path }}'

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and add to the movie queue
  Movie watchlist:
    imdb_list:
      list: watchlist
      user_id: '{{ secrets.imdb.user_id }}'
    movie_queue: add

  Movies:
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - kat:
            category: movies
            verified: yes

    template:
      - movies

  TV:
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: '{{ secrets.trakt.tv_list }}'
          type: shows
      settings:
        exact: yes
        identified_by: ep

    discover:
      what:
        - emit_series: yes
      from:
        - kat:
            category: tv
            verified: yes

    template:
      - tv

  Stop seeding:
    clean_transmission:
      netrc: '{{ secrets.general.netrc_path }}'
      min_ratio: 1
    disable_builtins: [details]
