secrets: secrets.yml

templates:
  global:
    content_filter:
      reject:
        - '*.rar'

    # Ensure Mac friendly filenames/paths
    pathscrub: mac

    # Add the output plugin for Transmission
    transmission:
      host: '{{ secrets.general.transmission_host }}'
      netrc: '{{ secrets.general.netrc_path }}'
      main_file_only: yes

    # Ignore self-signed certificates
    verify_ssl_certificates: no

    # Play nicely with some of the source domains
    domain_delay:
      torrentz.eu: 1 seconds
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 1
      max_retries: 4

    # Make it look more like a real browser
    headers:
      User-Agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36"

  # TV shows
  tv:
    thetvdb_lookup: yes
    set:
      path: '{{ secrets.general.tv_path }}/{{ tvdb_series_name }}/Season {{ series_season }}'

    quality: hdtv+ !h265

  # Movies
  movies:
    seen_movies: strict

    set:                                                                                                               
      path: '{{ secrets.general.movies_path }}'

    quality: 720p+ hdtv+ !h265

    # Attempt to prevent bogus downloads
    imdb_required: yes

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and add to the movie list, imdb_watchlist
  movie_watchlist:
    interval: 24 hours
    imdb_list:
      login: '{{ secrets.imdb.login }}'
      password: '{{ secrets.imdb.password }}'
      list: watchlist
    list_add:
      - movie_list: imdb_watchlist
    accept_all: yes

    # Do not apply the global template
    template: no_global

  movies:
    interval: 12 hours
    discover:
      what:
        - movie_list: imdb_watchlist
      from:
        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}%20category:movies%20verified:1/?rss=1
        - torrentz: verified
    list_queue:
      - movie_list: imdb_watchlist

    template:
      - movies

  tv:
    interval: 4 hours
    configure_series:
      from:
        trakt_list:
          username: '{{ secrets.trakt.username }}'
          list: '{{ secrets.trakt.tv_list }}'
          type: shows
      settings:
        exact: yes
        identified_by: ep
        upgrade: no

    discover:
      what:
        - emit_series:
            from_start: yes
      from:
        - search_rss: https://kickass.unblocked.la/usearch/{{search_term}}%20category:tv%20verified:1/?rss=1
        - torrentz: verified

    template:
      - tv

  stop_seeding:
    interval: 1 hours
    clean_transmission:
      host: '{{ secrets.general.transmission_host }}'
      netrc: '{{ secrets.general.netrc_path }}'
      min_ratio: 1
    disable: [details]
    template: no_global
