secrets: secrets.yml

templates:
  global:
    content_filter:
      reject: '*.rar'

    # Ensure Mac friendly filenames/paths
    pathscrub: mac

  # TV shows
  tv:
    exists_series:
      path: '{{ secrets.general.tv_path }}'
      allow_different_qualities: yes

    thetvdb_lookup: yes
    set:
      path: '{{ secrets.general.tv_path }}/{{ series_name|replace(":"," -") }}/Season {{ series_season }}'

    configure_series:
      settings:
        exact: yes
      from:
        thetvdb_favorites:
          account_id: '{{ secrets.thetvdb.account_id }}'
          strip_dates: yes

    quality: hdtv+

    discover:
      what:
        - emit_series: yes
      from:
        - kat:
            category: tv
            verified: yes

    # Add the output plugin for Transmission
    transmission:
      netrc: '{{ secrets.general.netrc_path }}'

  # Movies
  movies:
    exists_movie: '{{ secrets.general.movies_path }}'
    seen_movies: strict

    set:                                                                                                               
      path: '{{ secrets.general.movies_path }}'

    movie_queue:
      action: add
      quality: 720p+ hdtv+

    discover:
      what:
        - emit_movie_queue: yes
      from:
        - kat:
            category: movies
            verified: yes

    # Don't download movies already rated 
    crossmatch:
      from:
        - imdb_list:
            list: ratings
            user_id: '{{ secrets.imdb.user_id }}'
      fields:
        - imdb_id
      action: reject

    # Attempt to prevent bogus downloads
    imdb_required: yes

    # Add the output plugin for Transmission
    transmission:
      netrc: '{{ secrets.general.netrc_path }}'

# Tasks
tasks:
  # Fetch titles from an IMDB watchlist and add to the movie queue
  Watchlist:
    imdb_list:
      list: watchlist
      user_id: '{{ secrets.imdb.user_id }}'
    accept_all: yes
    queue_movies: yes

  Movies:
    template:
      - movies

  TV:
    template:
      - tv

  Stop seeding:
    clean_transmission:
      netrc: '{{ secrets.general.netrc_path }}'
      min_ratio: 1
